package com.biit.abcd.webpages.elements.formmanager;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.biit.abcd.MessageManager;
import com.biit.abcd.authentication.UserSessionHandler;
import com.biit.abcd.core.drools.FormToDroolsExporter;
import com.biit.abcd.core.drools.json.globalvariables.AbcdGlobalVariablesToJson;
import com.biit.abcd.core.drools.rules.exceptions.DroolsRuleGenerationException;
import com.biit.abcd.core.drools.rules.exceptions.InvalidRuleException;
import com.biit.abcd.language.LanguageCodes;
import com.biit.abcd.logger.AbcdLogger;
import com.biit.abcd.utils.ZipUtils;
import com.biit.abcd.webpages.components.SaveAction;
import com.biit.abcd.webpages.components.SettingsWindow;
import com.biit.persistence.dao.exceptions.UnexpectedDatabaseException;

public class SaveDroolsRulesAction implements SaveAction {

	@Override
	public String getMimeType() {
		return "application/zip";
	}

	@Override
	public String getExtension() {
		return "zip";
	}

	@Override
	public byte[] getInformationData() {
		try {
			List<String> filesToZip = new ArrayList<>();
			List<String> namesOfFiles = new ArrayList<>();
			FormToDroolsExporter droolsExporter = new FormToDroolsExporter();
			String rules = droolsExporter.getDroolRules(UserSessionHandler.getFormController().getForm(),
					UserSessionHandler.getGlobalVariablesController().getGlobalVariables());
			filesToZip.add(rules);
			Integer formVersion = UserSessionHandler.getFormController().getForm().getVersion();
			namesOfFiles.add("droolsRules_v" + formVersion + ".drl");
			String variables = AbcdGlobalVariablesToJson.toJson(UserSessionHandler.getGlobalVariablesController()
					.getGlobalVariables());
			filesToZip.add(variables);
			namesOfFiles.add("globalVariables_v" + formVersion + ".json");

			try {
				return ZipUtils.createZipFile(filesToZip, namesOfFiles);
			} catch (IOException e) {
				MessageManager.showError(LanguageCodes.ZIP_FILE_NOT_GENERATED);
				AbcdLogger.errorMessage(SettingsWindow.class.getName(), e);
			}
		} catch (UnexpectedDatabaseException e) {
			AbcdLogger.errorMessage(SettingsWindow.class.getName(), e);
			MessageManager.showError(LanguageCodes.ERROR_TITLE, LanguageCodes.ERROR_DATABASE_UNEXPECTED_EXCEPTION);

		} catch (DroolsRuleGenerationException e) {
			// Exception generated by the expression validator
			// We show the user the invalid rule name
			if (e.getGeneratedException() instanceof InvalidRuleException) {
				AbcdLogger.errorMessage(SettingsWindow.class.getName(), e.getGeneratedException());
				MessageManager.showError(LanguageCodes.ERROR_TITLE, LanguageCodes.DROOLS_RULE_INVALID,
						((InvalidRuleException) e.getGeneratedException()).getRuleName());
			} else {
				// This is a generic exception for everything related with the
				// rules generation
				// The exception that triggered the launch of this exception is
				// inside the received exception
				AbcdLogger.errorMessage(SettingsWindow.class.getName(), e.getGeneratedException());
				MessageManager.showError(LanguageCodes.ERROR_TITLE, LanguageCodes.DROOLS_RULES_GENERATION_EXCEPTION);
			}
		}
		return null;
	}

	@Override
	public boolean isValid() {
		return true;
	}

	@Override
	public String getFileName() {
		return "rules." + getExtension();
	}

}