package com.biit.abcd.core.testscenarios.validator;

import java.util.Arrays;
import java.util.List;

/**
 *	Keeps the message identifier code generated by the validation report and the parameters associated 
 */
public class TestScenarioValidatorMessage {
	
	// Code identifying the message to translate
	// The code must be in the localization file
	private String code;
	private List<String> parameters;
	
	public TestScenarioValidatorMessage(String codeIdentifier, List<String> parameters){
		this.code = codeIdentifier;
		this.parameters = parameters;
	}
	
	public TestScenarioValidatorMessage(String codeIdentifier, String...parameters){
		this.code = codeIdentifier;
		this.parameters = Arrays.asList(parameters);
	}
	
	public String getCode() {
		return code;
	}
	public void setCodeIdentifier(String code) {
		this.code = code;
	}
	public List<String> getParameters() {
		return parameters;
	}
	public void setParameters(List<String> parameters) {
		this.parameters = parameters;
	}
	
	
	
}
