package com.biit.abcd.core.testscenarios.validator;

/*-
 * #%L
 * Agile Business sCenario Designer Tool (Core)
 * %%
 * Copyright (C) 2022 - 2025 BiiT Sourcing Solutions S.L.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import java.util.Arrays;
import java.util.List;

/**
 *	Keeps the message identifier code generated by the validation report and the parameters associated 
 */
public class TestScenarioValidatorMessage {
	
	// Code identifying the message to translate
	// The code must be in the localization file
	private String code;
	private List<String> parameters;
	
	public TestScenarioValidatorMessage(String codeIdentifier, List<String> parameters){
		this.code = codeIdentifier;
		this.parameters = parameters;
	}
	
	public TestScenarioValidatorMessage(String codeIdentifier, String...parameters){
		this.code = codeIdentifier;
		this.parameters = Arrays.asList(parameters);
	}
	
	public String getCode() {
		return code;
	}
	public void setCodeIdentifier(String code) {
		this.code = code;
	}
	public List<String> getParameters() {
		return parameters;
	}
	public void setParameters(List<String> parameters) {
		this.parameters = parameters;
	}
	
	
	
}
