package com.biit.drools 
import com.biit.abcd.core.drools.facts.inputform.* 
import com.biit.abcd.core.drools.utils.* 
import java.util.Date 
import java.util.List 
import com.biit.abcd.logger.AbcdLogger 
rule "BaseTable_row_0"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$0e8415c238d44d08b09655c207f874a8 : Question( getAnswer() == 'Financien.Inkomen.RuimVoldoende') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$0e8415c238d44d08b09655c207f874a8.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Inkomen, qScore, 5.0)");

end
rule "BaseTable_row_1"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$0e8415c238d44d08b09655c207f874a8 : Question( getAnswer() == 'Financien.Inkomen.NetVoldoendeZonderUitkering') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$0e8415c238d44d08b09655c207f874a8.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Inkomen, qScore, 4.0)");

end
rule "BaseTable_row_2"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$0e8415c238d44d08b09655c207f874a8 : Question( getAnswer() == 'Financien.Inkomen.VoldoendeMetUitkering') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$0e8415c238d44d08b09655c207f874a8.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Inkomen, qScore, 3.0)");

end
rule "BaseTable_row_3"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$0e8415c238d44d08b09655c207f874a8 : Question( getAnswer() == 'Financien.Inkomen.Onvoldoende') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$0e8415c238d44d08b09655c207f874a8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Inkomen, qScore, 2.0)");

end
rule "BaseTable_row_4"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$0e8415c238d44d08b09655c207f874a8 : Question( getAnswer() == 'Financien.Inkomen.Geen') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$0e8415c238d44d08b09655c207f874a8.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Inkomen, qScore, 1.0)");

end
rule "BaseTable_row_5"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$f2a0d930f63540fc818c855a751eb30b : Question( getAnswer() == 'Financien.Schulden.Sparen') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$f2a0d930f63540fc818c855a751eb30b.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Schulden, qScore, 5.0)");

end
rule "BaseTable_row_6"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$f2a0d930f63540fc818c855a751eb30b : Question( getAnswer() == 'Financien.Schulden.NietSparenGeenSchulden') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$f2a0d930f63540fc818c855a751eb30b.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Schulden, qScore, 4.0)");

end
rule "BaseTable_row_7"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$f2a0d930f63540fc818c855a751eb30b : Question( getAnswer() == 'Financien.Schulden.NemenAf') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$f2a0d930f63540fc818c855a751eb30b.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Schulden, qScore, 4.0)");

end
rule "BaseTable_row_8"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$f2a0d930f63540fc818c855a751eb30b : Question( getAnswer() == 'Financien.Schulden.BlijvenGelijk') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$f2a0d930f63540fc818c855a751eb30b.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Schulden, qScore, 3.0)");

end
rule "BaseTable_row_9"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$f2a0d930f63540fc818c855a751eb30b : Question( getAnswer() == 'Financien.Schulden.NemenToe') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$f2a0d930f63540fc818c855a751eb30b.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Schulden, qScore, 2.0)");

end
rule "BaseTable_row_10"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$ea8c1405bdbb40f395eee5d510faf1b2 : Question( getAnswer() == 'Financien.UItgaven.OnverstandigGeen') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$ea8c1405bdbb40f395eee5d510faf1b2.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Uitgaven, qScore, 5.0)");

end
rule "BaseTable_row_11"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$ea8c1405bdbb40f395eee5d510faf1b2 : Question( getAnswer() == 'Financien.Uitgaven.OnverstandigWelVeroorloven') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$ea8c1405bdbb40f395eee5d510faf1b2.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Uitgaven, qScore, 5.0)");

end
rule "BaseTable_row_12"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$ea8c1405bdbb40f395eee5d510faf1b2 : Question( getAnswer() == 'Financien.Uitgaven.OnverstandigSomsNietVeroorloven') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$ea8c1405bdbb40f395eee5d510faf1b2.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Uitgaven, qScore, 3.0)");

end
rule "BaseTable_row_13"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$ea8c1405bdbb40f395eee5d510faf1b2 : Question( getAnswer() == 'Financien.Uitgaven.OnverstandigRegelmatigNiet') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$ea8c1405bdbb40f395eee5d510faf1b2.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Uitgaven, qScore, 2.0)");

end
rule "BaseTable_row_14"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$3393b8d1484f4e0cbe565ec488798f24 : Question( getAnswer() == 'Financien.Beheer.VolledigInzicht') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$3393b8d1484f4e0cbe565ec488798f24.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Beheer, qScore, 5.0)");

end
rule "BaseTable_row_15"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$3393b8d1484f4e0cbe565ec488798f24 : Question( getAnswer() == 'Financien.Beheer.RedelijkInzicht') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$3393b8d1484f4e0cbe565ec488798f24.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Beheer, qScore, 4.0)");

end
rule "BaseTable_row_16"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$3393b8d1484f4e0cbe565ec488798f24 : Question( getAnswer() == 'Financien.Beheer.WelEensVerrast') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$3393b8d1484f4e0cbe565ec488798f24.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Beheer, qScore, 3.0)");

end
rule "BaseTable_row_17"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$3393b8d1484f4e0cbe565ec488798f24 : Question( getAnswer() == 'Financien.Beheer.VeelVerrassingen') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$3393b8d1484f4e0cbe565ec488798f24.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Beheer, qScore, 2.0)");

end
rule "BaseTable_row_18"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$3393b8d1484f4e0cbe565ec488798f24 : Question( getAnswer() == 'Financien.Beheer.Spoorbijster') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$3393b8d1484f4e0cbe565ec488798f24.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Beheer, qScore, 1.0)");

end
rule "BaseTable_row_19"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') and
	$598e8390d90147eb8f19f3169a00cc93 : Question( getAnswer() == 'Financien.Beheer.Hulp.Ja') from $f3da6244386a4106869ef098582fee92.getQuestions()
)
then
	$598e8390d90147eb8f19f3169a00cc93.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Financien.Beheer.Hulp, qScore, 3.0)");

end
rule "BaseTable_row_20"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.Vast') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 5.0)");

end
rule "BaseTable_row_21"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.Tijdelijk') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 4.0)");

end
rule "BaseTable_row_22"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.Bijbaan') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 4.0)");

end
rule "BaseTable_row_23"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.OpleidingHoger') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 5.0)");

end
rule "BaseTable_row_24"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.Opleidng Voor') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 4.0)");

end
rule "BaseTable_row_25"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.Stage') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 4.0)");

end
rule "BaseTable_row_26"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$c6b41049f77c44d5965f03128d14e458 : Question( getAnswer() == 'Dagbesteding.Werk.Niets') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$c6b41049f77c44d5965f03128d14e458.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Werk, qScore, 3.0)");

end
rule "BaseTable_row_27"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$75692bb07bde47099875f4dc4eea2196 : Question( getAnswer() == 'Dagbesteding.Ondersteuning.Werk') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$75692bb07bde47099875f4dc4eea2196.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Ondersteuning, qScore, 3.0)");

end
rule "BaseTable_row_28"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$75692bb07bde47099875f4dc4eea2196 : Question( getAnswer() == 'Dagbesteding.Ondersteuning.Ritme') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$75692bb07bde47099875f4dc4eea2196.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Ondersteuning, qScore, 3.0)");

end
rule "BaseTable_row_29"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$75692bb07bde47099875f4dc4eea2196 : Question( getAnswer() == 'Dagbesteding.Ondersteuning.WilWel') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$75692bb07bde47099875f4dc4eea2196.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Ondersteuning, qScore, 2.0)");

end
rule "BaseTable_row_30"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$75692bb07bde47099875f4dc4eea2196 : Question( getAnswer() == 'Dagbesteding.Ondersteuning.WilNiet') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$75692bb07bde47099875f4dc4eea2196.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Ondersteuning, qScore, 2.0)");

end
rule "BaseTable_row_31"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$89a8ac9e4694486b9a40843c29b4e569 : Question( getAnswer() == 'Dagbesteding.Bezigheid.Goed') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$89a8ac9e4694486b9a40843c29b4e569.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Bezigheid, qScore, 5.0)");

end
rule "BaseTable_row_32"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$89a8ac9e4694486b9a40843c29b4e569 : Question( getAnswer() == 'Dagbesteding.Bezigheid.Redelijk') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$89a8ac9e4694486b9a40843c29b4e569.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Bezigheid, qScore, 3.0)");

end
rule "BaseTable_row_33"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$89a8ac9e4694486b9a40843c29b4e569 : Question( getAnswer() == 'Dagbesteding.Bezigheid.Onvoldoende') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$89a8ac9e4694486b9a40843c29b4e569.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Bezigheid, qScore, 1.0)");

end
rule "BaseTable_row_34"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$15e4bcae63ca4a0c80ae76abea938982 : Question( getAnswer() == 'Dagbesteding.Overlast.Geen') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$15e4bcae63ca4a0c80ae76abea938982.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Overlast, qScore, 5.0)");

end
rule "BaseTable_row_35"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$15e4bcae63ca4a0c80ae76abea938982 : Question( getAnswer() == 'Dagbesteding.Overlast.Wel') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$15e4bcae63ca4a0c80ae76abea938982.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Overlast, qScore, 2.0)");

end
rule "BaseTable_row_36"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f23e7a7ec8074bceb50012975e7c3e9e : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Dagbesteding') and
	$15e4bcae63ca4a0c80ae76abea938982 : Question( getAnswer() == 'Dagbesteding.Overlast.Buren') from $f23e7a7ec8074bceb50012975e7c3e9e.getQuestions()
)
then
	$15e4bcae63ca4a0c80ae76abea938982.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Dagbesteding.Overlast, qScore, 1.0)");

end
rule "BaseTable_row_37"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$52cd6c288e2b4ea5bbf851477f212f07 : Question( getAnswer() == 'Huisvesting.Veilig.Ja') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$52cd6c288e2b4ea5bbf851477f212f07.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Veiligheid, qScore, 5.0)");

end
rule "BaseTable_row_38"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$52cd6c288e2b4ea5bbf851477f212f07 : Question( getAnswer() == 'Huisvesting.Veilig.Gebreken') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$52cd6c288e2b4ea5bbf851477f212f07.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Veiligheid, qScore, 4.0)");

end
rule "BaseTable_row_39"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$52cd6c288e2b4ea5bbf851477f212f07 : Question( getAnswer() == 'Huisvesting.Veilig.Achterstallig') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$52cd6c288e2b4ea5bbf851477f212f07.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Veiligheid, qScore, 3.0)");

end
rule "BaseTable_row_40"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$52cd6c288e2b4ea5bbf851477f212f07 : Question( getAnswer() == 'Huisvesting.Veilig.Woninguitzetting') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$52cd6c288e2b4ea5bbf851477f212f07.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Veiligheid, qScore, 2.0)");

end
rule "BaseTable_row_41"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$52cd6c288e2b4ea5bbf851477f212f07 : Question( getAnswer() == 'Huisvesting.Veilig.Ongeschikt') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$52cd6c288e2b4ea5bbf851477f212f07.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Veiligheid, qScore, 2.0)");

end
rule "BaseTable_row_42"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$52cd6c288e2b4ea5bbf851477f212f07 : Question( getAnswer() == 'Huisvesting.Veilig.Dakloos') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$52cd6c288e2b4ea5bbf851477f212f07.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Veiligheid, qScore, 2.0)");

end
rule "BaseTable_row_43"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$074f3fb4c344444fb1a702da9a91beda : Question( getAnswer() == 'Huisvesting.Gebruik.Groot') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$074f3fb4c344444fb1a702da9a91beda.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Gebruik, qScore, 5.0)");

end
rule "BaseTable_row_44"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$074f3fb4c344444fb1a702da9a91beda : Question( getAnswer() == 'Huisvesting.Gebruik.Goed') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$074f3fb4c344444fb1a702da9a91beda.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Gebruik, qScore, 5.0)");

end
rule "BaseTable_row_45"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$074f3fb4c344444fb1a702da9a91beda : Question( getAnswer() == 'Huisvesting.Gebruik.Lichamelijk') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$074f3fb4c344444fb1a702da9a91beda.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Gebruik, qScore, 2.0)");

end
rule "BaseTable_row_46"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$074f3fb4c344444fb1a702da9a91beda : Question( getAnswer() == 'Huisvesting.Gebruik.Past') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$074f3fb4c344444fb1a702da9a91beda.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Gebruik, qScore, 3.0)");

end
rule "BaseTable_row_47"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$074f3fb4c344444fb1a702da9a91beda : Question( getAnswer() == 'Huisvesting.Gebruik.TeKlein') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$074f3fb4c344444fb1a702da9a91beda.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Gebruik, qScore, 2.0)");

end
rule "BaseTable_row_48"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Vast') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 5.0)");

end
rule "BaseTable_row_49"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Tijdelijk') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 4.0)");

end
rule "BaseTable_row_50"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Ouders') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 3.0)");

end
rule "BaseTable_row_51"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Samenwonend') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 3.0)");

end
rule "BaseTable_row_52"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Onderhuur') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 3.0)");

end
rule "BaseTable_row_53"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Logeren') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 2.0)");

end
rule "BaseTable_row_54"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$f159f0df6d9d445c90814bafa606efbd : Question( getAnswer() == 'Huisvesting.Contract.Straat') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$f159f0df6d9d445c90814bafa606efbd.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract, qScore, 1.0)");

end
rule "BaseTable_row_55"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$8af9e3f9736a49189bc9791af0ccb9e2 : Question( getAnswer() == 'Huisvesting.Contract.Tijdelijk') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$8af9e3f9736a49189bc9791af0ccb9e2.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract2, qScore, 5.0)");

end
rule "BaseTable_row_56"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$8af9e3f9736a49189bc9791af0ccb9e2 : Question( getAnswer() == 'Huisvesting.Contract.Ouders') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$8af9e3f9736a49189bc9791af0ccb9e2.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract2, qScore, 4.0)");

end
rule "BaseTable_row_57"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$8af9e3f9736a49189bc9791af0ccb9e2 : Question( getAnswer() == 'Huisvesting.Contract.Samenwonend') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$8af9e3f9736a49189bc9791af0ccb9e2.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract2, qScore, 3.0)");

end
rule "BaseTable_row_58"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$8af9e3f9736a49189bc9791af0ccb9e2 : Question( getAnswer() == 'Huisvesting.Contract.Onderhuur') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$8af9e3f9736a49189bc9791af0ccb9e2.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract2, qScore, 3.0)");

end
rule "BaseTable_row_59"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$8af9e3f9736a49189bc9791af0ccb9e2 : Question( getAnswer() == 'Huisvesting.Contract.Logeren') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$8af9e3f9736a49189bc9791af0ccb9e2.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract2, qScore, 3.0)");

end
rule "BaseTable_row_60"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$71f53e9bd6094cf4b173dc2bedbfada8 : Question( getAnswer() == 'Huisvesting.Contract.Logeren') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$71f53e9bd6094cf4b173dc2bedbfada8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract3, qScore, 2.0)");

end
rule "BaseTable_row_61"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$71f53e9bd6094cf4b173dc2bedbfada8 : Question( getAnswer() == 'Huisvesting.Contract.Straat') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$71f53e9bd6094cf4b173dc2bedbfada8.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Contract3, qScore, 1.0)");

end
rule "BaseTable_row_62"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$55c0465cac2f4433a487f07fab9a32e8 : Question( getAnswer() == 'Huisvesting.Huur.Betaalbaar') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$55c0465cac2f4433a487f07fab9a32e8.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur, qScore, 5.0)");

end
rule "BaseTable_row_63"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$55c0465cac2f4433a487f07fab9a32e8 : Question( getAnswer() == 'Huisvesting.Huur.Duur') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$55c0465cac2f4433a487f07fab9a32e8.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur, qScore, 3.0)");

end
rule "BaseTable_row_64"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$55c0465cac2f4433a487f07fab9a32e8 : Question( getAnswer() == 'Huisvesting.Huur.Achterstand') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$55c0465cac2f4433a487f07fab9a32e8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur, qScore, 2.0)");

end
rule "BaseTable_row_65"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$55c0465cac2f4433a487f07fab9a32e8 : Question( getAnswer() == 'Huisvesting.Huur.Problemen') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$55c0465cac2f4433a487f07fab9a32e8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur, qScore, 2.0)");

end
rule "BaseTable_row_66"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$55c0465cac2f4433a487f07fab9a32e8 : Question( getAnswer() == 'Huisvesting.Huur.NietBetalen') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$55c0465cac2f4433a487f07fab9a32e8.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur, qScore, 1.0)");

end
rule "BaseTable_row_67"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$bb089a6dbd544e29b49ee69763822bf8 : Question( getAnswer() == 'Huisvesting.Huur.Problemen') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$bb089a6dbd544e29b49ee69763822bf8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur2, qScore, 2.0)");

end
rule "BaseTable_row_68"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$6c12e9537d29480abdc2023e8bf7cd1a : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huisvesting') and
	$bb089a6dbd544e29b49ee69763822bf8 : Question( getAnswer() == 'Huisvesting.Huur,NietBetalen') from $6c12e9537d29480abdc2023e8bf7cd1a.getQuestions()
)
then
	$bb089a6dbd544e29b49ee69763822bf8.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Huisvesting.Huur2, qScore, 1.0)");

end
rule "BaseTable_row_69"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$d023c91b91ca46cd9d45847d1a7ea480 : Question( getAnswer() == 'Gezin.Samenstelling.Alleen') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$d023c91b91ca46cd9d45847d1a7ea480.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samenstelling, qScore, 4.0)");

end
rule "BaseTable_row_70"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$d023c91b91ca46cd9d45847d1a7ea480 : Question( getAnswer() == 'Gezin.Samenstelling.Ouders') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$d023c91b91ca46cd9d45847d1a7ea480.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samenstelling, qScore, 5.0)");

end
rule "BaseTable_row_71"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$d023c91b91ca46cd9d45847d1a7ea480 : Question( getAnswer() == 'Gezin.Samenstelling.Alleen+') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$d023c91b91ca46cd9d45847d1a7ea480.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samenstelling, qScore, 5.0)");

end
rule "BaseTable_row_72"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$d023c91b91ca46cd9d45847d1a7ea480 : Question( getAnswer() == 'Gezin.Samensteling.Gehuwd') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$d023c91b91ca46cd9d45847d1a7ea480.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samenstelling, qScore, 5.0)");

end
rule "BaseTable_row_73"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$d023c91b91ca46cd9d45847d1a7ea480 : Question( getAnswer() == 'Gezin.Samenstelling.Gehuwd+') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$d023c91b91ca46cd9d45847d1a7ea480.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samenstelling, qScore, 5.0)");

end
rule "BaseTable_row_74"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$bca11fd5144c49cc9e7e5ec6f2588708 : Question( getAnswer() == 'Gezin.Samengaan.Harmonie') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$bca11fd5144c49cc9e7e5ec6f2588708.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samengaan, qScore, 5.0)");

end
rule "BaseTable_row_75"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$bca11fd5144c49cc9e7e5ec6f2588708 : Question( getAnswer() == 'Gezin.Samengaan.ProblemenVoorbij') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$bca11fd5144c49cc9e7e5ec6f2588708.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samengaan, qScore, 4.0)");

end
rule "BaseTable_row_76"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$bca11fd5144c49cc9e7e5ec6f2588708 : Question( getAnswer() == 'Gezin.Samengaan.ProblemenHanteerbaar') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$bca11fd5144c49cc9e7e5ec6f2588708.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samengaan, qScore, 3.0)");

end
rule "BaseTable_row_77"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$bca11fd5144c49cc9e7e5ec6f2588708 : Question( getAnswer() == 'Gezin.Samengaan.Ontlopen') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$bca11fd5144c49cc9e7e5ec6f2588708.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samengaan, qScore, 2.0)");

end
rule "BaseTable_row_78"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$bca11fd5144c49cc9e7e5ec6f2588708 : Question( getAnswer() == 'Gezin.Samengaan.VeelProblemen') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$bca11fd5144c49cc9e7e5ec6f2588708.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Samengaan, qScore, 1.0)");

end
rule "BaseTable_row_79"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$06d48325fe514e1d8ddfc00674a0b9d8 : Question( getAnswer() == 'Gezin.Druk.Geen') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$06d48325fe514e1d8ddfc00674a0b9d8.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Druk, qScore, 5.0)");

end
rule "BaseTable_row_80"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$06d48325fe514e1d8ddfc00674a0b9d8 : Question( getAnswer() == 'Gezin.Druk.Draagbaar') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$06d48325fe514e1d8ddfc00674a0b9d8.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Druk, qScore, 3.0)");

end
rule "BaseTable_row_81"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$06d48325fe514e1d8ddfc00674a0b9d8 : Question( getAnswer() == 'Gezin.Druk.Groot') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$06d48325fe514e1d8ddfc00674a0b9d8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Druk, qScore, 2.0)");

end
rule "BaseTable_row_82"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$06d48325fe514e1d8ddfc00674a0b9d8 : Question( getAnswer() == 'Gezin.Druk.Verwaarlozing') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$06d48325fe514e1d8ddfc00674a0b9d8.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Druk, qScore, 1.0)");

end
rule "BaseTable_row_83"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$06d48325fe514e1d8ddfc00674a0b9d8 : Question( getAnswer() == 'Gezin.Druk.Hanteerbaar') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$06d48325fe514e1d8ddfc00674a0b9d8.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Druk, qScore, 3.0)");

end
rule "BaseTable_row_84"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$06d48325fe514e1d8ddfc00674a0b9d8 : Question( getAnswer() == 'Gezin.Druk.Onhanteerbaar') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$06d48325fe514e1d8ddfc00674a0b9d8.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Druk, qScore, 2.0)");

end
rule "BaseTable_row_85"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.Geen') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 5.0)");

end
rule "BaseTable_row_86"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.Geschreeuw') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 3.0)");

end
rule "BaseTable_row_87"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.Soms') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 1.0)");

end
rule "BaseTable_row_88"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.Regelmatig') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 1.0)");

end
rule "BaseTable_row_89"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.Tik?') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 2.0)");

end
rule "BaseTable_row_90"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.Intimideren') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 3.0)");

end
rule "BaseTable_row_91"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.CorrigerendeTik') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 1.0)");

end
rule "BaseTable_row_92"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$1fb75236ef51462ab07792d10e7841bb : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Huiselijke relaties') and
	$495a4ff0d37846cab879978041b50f8a : Question( getAnswer() == 'Gezin.Geweld.TikGoed') from $1fb75236ef51462ab07792d10e7841bb.getQuestions()
)
then
	$495a4ff0d37846cab879978041b50f8a.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Gezin.Geweld, qScore, 1.0)");

end
rule "BaseTable_row_93"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$8bc574504be54a559e3d10af70d435e0 : Question( getAnswer() == 'Geestelijk.Aandoening.Geen') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$8bc574504be54a559e3d10af70d435e0.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Aandoening, qScore, 5.0)");

end
rule "BaseTable_row_94"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$8bc574504be54a559e3d10af70d435e0 : Question( getAnswer() == 'Geestelijk.Aandoening.Soms') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$8bc574504be54a559e3d10af70d435e0.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Aandoening, qScore, 4.0)");

end
rule "BaseTable_row_95"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$8bc574504be54a559e3d10af70d435e0 : Question( getAnswer() == 'Geestelijk.Aandoening.Vaak') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$8bc574504be54a559e3d10af70d435e0.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Aandoening, qScore, 3.0)");

end
rule "BaseTable_row_96"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$8bc574504be54a559e3d10af70d435e0 : Question( getAnswer() == 'Geestelijk.Aandoening.Altijd') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$8bc574504be54a559e3d10af70d435e0.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Aandoening, qScore, 2.0)");

end
rule "BaseTable_row_97"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$8bc574504be54a559e3d10af70d435e0 : Question( getAnswer() == 'Geestelijk.Aandoening.Zelfmoord') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$8bc574504be54a559e3d10af70d435e0.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Aandoening, qScore, 1.0)");

end
rule "BaseTable_row_98"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$625a4d325347404887f075e72e88400e : Question( getAnswer() == 'Geestelijk.Functioneren.Goed') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$625a4d325347404887f075e72e88400e.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Functioneren, qScore, 5.0)");

end
rule "BaseTable_row_99"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$625a4d325347404887f075e72e88400e : Question( getAnswer() == 'Geestelijk.Functioneren.AfEnToe') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$625a4d325347404887f075e72e88400e.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Functioneren, qScore, 4.0)");

end
rule "BaseTable_row_100"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$625a4d325347404887f075e72e88400e : Question( getAnswer() == 'Geestelijk.Functioneren.Regelmatig') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$625a4d325347404887f075e72e88400e.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Functioneren, qScore, 3.0)");

end
rule "BaseTable_row_101"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$625a4d325347404887f075e72e88400e : Question( getAnswer() == 'Geestelijk.Functioneren.Aanhoudend') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$625a4d325347404887f075e72e88400e.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Functioneren, qScore, 2.0)");

end
rule "BaseTable_row_102"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$625a4d325347404887f075e72e88400e : Question( getAnswer() == 'Geestelijk.Functioneren.Gevaar') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$625a4d325347404887f075e72e88400e.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Functioneren, qScore, 1.0)");

end
rule "BaseTable_row_103"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.Geen') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 5.0)");

end
rule "BaseTable_row_104"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.Arts') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 4.0)");

end
rule "BaseTable_row_105"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.Regelmatig') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 4.0)");

end
rule "BaseTable_row_106"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.Vergeten') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 2.0)");

end
rule "BaseTable_row_107"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.Kosten') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 1.0)");

end
rule "BaseTable_row_108"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.VergeetVaak') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 1.0)");

end
rule "BaseTable_row_109"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$420dc41617a24992bbd988a084fb6250 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Geestelijke gezondheid') and
	$0598132f00bb477786a3dff55ebc8458 : Question( getAnswer() == 'Geestelijk.Behandeling.Moeten') from $420dc41617a24992bbd988a084fb6250.getQuestions()
)
then
	$0598132f00bb477786a3dff55ebc8458.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Geestelijk.Behandeling, qScore, 1.0)");

end
rule "BaseTable_row_110"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$0bdba466e3b24e2f8ddf76e98885f78c : Question( getAnswer() == 'Licahmelijk.Aandoeningen.Gezond') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$0bdba466e3b24e2f8ddf76e98885f78c.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Aandoeningen, qScore, 5.0)");

end
rule "BaseTable_row_111"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$0bdba466e3b24e2f8ddf76e98885f78c : Question( getAnswer() == 'Lichamelijk.Aandoeningen.Enkele') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$0bdba466e3b24e2f8ddf76e98885f78c.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Aandoeningen, qScore, 4.0)");

end
rule "BaseTable_row_112"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$0bdba466e3b24e2f8ddf76e98885f78c : Question( getAnswer() == 'Lichamelijk.Aandoeningen.Meerdere') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$0bdba466e3b24e2f8ddf76e98885f78c.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Aandoeningen, qScore, 3.0)");

end
rule "BaseTable_row_113"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$0bdba466e3b24e2f8ddf76e98885f78c : Question( getAnswer() == 'Lichamelijk.Aandoeningen.Ernstig') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$0bdba466e3b24e2f8ddf76e98885f78c.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Aandoeningen, qScore, 2.0)");

end
rule "BaseTable_row_114"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$0bdba466e3b24e2f8ddf76e98885f78c : Question( getAnswer() == 'Lichamelijk.Aandoeningen.NietFunctioneren') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$0bdba466e3b24e2f8ddf76e98885f78c.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Aandoeningen, qScore, 1.0)");

end
rule "BaseTable_row_115"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$37cac36469be488babd2e86f9474e850 : Question( getAnswer() == 'Lichamelijk.Behandeling.Geen') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$37cac36469be488babd2e86f9474e850.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Behandeling, qScore, 5.0)");

end
rule "BaseTable_row_116"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$37cac36469be488babd2e86f9474e850 : Question( getAnswer() == 'Lichamelijk.Behandeling.NietNoodzakelijk') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$37cac36469be488babd2e86f9474e850.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Behandeling, qScore, 4.0)");

end
rule "BaseTable_row_117"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$37cac36469be488babd2e86f9474e850 : Question( getAnswer() == 'Lichamelijk.Behandeling.Regelmatig') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$37cac36469be488babd2e86f9474e850.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Behandeling, qScore, 4.0)");

end
rule "BaseTable_row_118"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$37cac36469be488babd2e86f9474e850 : Question( getAnswer() == 'Lichamelijk.Behandeling.Vergeet') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$37cac36469be488babd2e86f9474e850.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Behandeling, qScore, 2.0)");

end
rule "BaseTable_row_119"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$568e394680214f13b7acec839bf4518c : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Lichamelijke gezondheid') and
	$37cac36469be488babd2e86f9474e850 : Question( getAnswer() == 'Lichamelijk.Behandeling.NogNiet') from $568e394680214f13b7acec839bf4518c.getQuestions()
)
then
	$37cac36469be488babd2e86f9474e850.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Lichamelijk.Behandeling, qScore, 1.0)");

end
rule "BaseTable_row_120"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Geen') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 5.0)");

end
rule "BaseTable_row_121"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.30niet') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 5.0)");

end
rule "BaseTable_row_122"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Wel') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 3.0)");

end
rule "BaseTable_row_123"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Afgekickt') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 4.0)");

end
rule "BaseTable_row_124"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Afkicken+') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 3.0)");

end
rule "BaseTable_row_125"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Afkicken-') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 2.0)");

end
rule "BaseTable_row_126"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Afkicken.Wil+') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 2.0)");

end
rule "BaseTable_row_127"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$1118f22a9d4d4f399952a7218b3b0700 : Question( getAnswer() == 'Verslaving.Aanwezig.Afkicken.Wil-') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$1118f22a9d4d4f399952a7218b3b0700.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Aanwezig, qScore, 1.0)");

end
rule "BaseTable_row_128"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$69c1003c39034baf886a90b9bac7aa70 : Question( getAnswer() == 'Verslaving.Behandeltrouw.NietNodig') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$69c1003c39034baf886a90b9bac7aa70.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw, qScore, 5.0)");

end
rule "BaseTable_row_129"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$69c1003c39034baf886a90b9bac7aa70 : Question( getAnswer() == 'Verslaving.Behandeltrouw.Terugval') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$69c1003c39034baf886a90b9bac7aa70.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw, qScore, 4.0)");

end
rule "BaseTable_row_130"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$69c1003c39034baf886a90b9bac7aa70 : Question( getAnswer() == 'Verslaving.Behandeltrouw.Intensief') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$69c1003c39034baf886a90b9bac7aa70.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw, qScore, 4.0)");

end
rule "BaseTable_row_131"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$69c1003c39034baf886a90b9bac7aa70 : Question( getAnswer() == 'Verslaving.Behandeltrouw.Afzeggen') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$69c1003c39034baf886a90b9bac7aa70.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw, qScore, 3.0)");

end
rule "BaseTable_row_132"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$69c1003c39034baf886a90b9bac7aa70 : Question( getAnswer() == 'Verslaving.Behandeltrouw.WeetNiet') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$69c1003c39034baf886a90b9bac7aa70.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw, qScore, 3.0)");

end
rule "BaseTable_row_133"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$69c1003c39034baf886a90b9bac7aa70 : Question( getAnswer() == 'Verslaving.Behandeltrouw.WilNiet') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$69c1003c39034baf886a90b9bac7aa70.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw, qScore, 1.0)");

end
rule "BaseTable_row_134"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$f49ac5f4ed0342a08a72bcd8acb47a55 : Question( getAnswer() == 'Verslaving.Behandeltrouw.NietNodig') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$f49ac5f4ed0342a08a72bcd8acb47a55.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw2, qScore, 2.0)");

end
rule "BaseTable_row_135"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$f49ac5f4ed0342a08a72bcd8acb47a55 : Question( getAnswer() == 'Verslaving.Behandeltrouw.Terugval') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$f49ac5f4ed0342a08a72bcd8acb47a55.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw2, qScore, 1.0)");

end
rule "BaseTable_row_136"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$4b7d50db6bad49b1b5bbf71b64fd1c95 : Question( getAnswer() == 'Verslaving.Behandeltrouw.Intensief') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$4b7d50db6bad49b1b5bbf71b64fd1c95.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw3, qScore, 3.0)");

end
rule "BaseTable_row_137"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$4b7d50db6bad49b1b5bbf71b64fd1c95 : Question( getAnswer() == 'Verslaving.Behandeltrouw.Afzeggen') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$4b7d50db6bad49b1b5bbf71b64fd1c95.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Behandeltrouw3, qScore, 4.0)");

end
rule "BaseTable_row_138"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$2acf022d019a4bd7ac73c88ceea90210 : Question( getAnswer() == 'Verslaving.Effect.Geen') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$2acf022d019a4bd7ac73c88ceea90210.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Effect, qScore, 5.0)");

end
rule "BaseTable_row_139"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$2acf022d019a4bd7ac73c88ceea90210 : Question( getAnswer() == 'Verslaving.Effect.RecentGeen') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$2acf022d019a4bd7ac73c88ceea90210.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Effect, qScore, 4.0)");

end
rule "BaseTable_row_140"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$2acf022d019a4bd7ac73c88ceea90210 : Question( getAnswer() == 'Verslaving.Effect.RecentWel') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$2acf022d019a4bd7ac73c88ceea90210.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Effect, qScore, 2.0)");

end
rule "BaseTable_row_141"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ca8da776e96e40e3a01c70c0a4fa38e0 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Alcohol-, drugs-, game- of gokverslaving') and
	$2acf022d019a4bd7ac73c88ceea90210 : Question( getAnswer() == 'Verslaving.Effect.Zorgelijk') from $ca8da776e96e40e3a01c70c0a4fa38e0.getQuestions()
)
then
	$2acf022d019a4bd7ac73c88ceea90210.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Verslaving.Effect, qScore, 1.0)");

end
rule "BaseTable_row_142"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1fd5cad4c16548b78450508c9d6a9bb2 : Question( getAnswer() == 'ADL.Huishouden.Alles') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1fd5cad4c16548b78450508c9d6a9bb2.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Huishouden, qScore, 5.0)");

end
rule "BaseTable_row_143"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1fd5cad4c16548b78450508c9d6a9bb2 : Question( getAnswer() == 'ADL.Huishouden.Bijna+') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1fd5cad4c16548b78450508c9d6a9bb2.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Huishouden, qScore, 4.0)");

end
rule "BaseTable_row_144"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1fd5cad4c16548b78450508c9d6a9bb2 : Question( getAnswer() == 'ADL.Huishouden.Niets+') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1fd5cad4c16548b78450508c9d6a9bb2.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Huishouden, qScore, 3.0)");

end
rule "BaseTable_row_145"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1fd5cad4c16548b78450508c9d6a9bb2 : Question( getAnswer() == 'ADL.Huishouden.Niets-') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1fd5cad4c16548b78450508c9d6a9bb2.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Huishouden, qScore, 2.0)");

end
rule "BaseTable_row_146"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$0243e22306c849b5bb8df2097c783abf : Question( getAnswer() == 'ADL.Organiseren.Zelf') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$0243e22306c849b5bb8df2097c783abf.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Organiseren, qScore, 5.0)");

end
rule "BaseTable_row_147"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$0243e22306c849b5bb8df2097c783abf : Question( getAnswer() == 'ADL.Organiseren.Oplosbaar') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$0243e22306c849b5bb8df2097c783abf.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Organiseren, qScore, 4.0)");

end
rule "BaseTable_row_148"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$0243e22306c849b5bb8df2097c783abf : Question( getAnswer() == 'ADL.Organiseren.WatHulp') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$0243e22306c849b5bb8df2097c783abf.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Organiseren, qScore, 3.0)");

end
rule "BaseTable_row_149"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$0243e22306c849b5bb8df2097c783abf : Question( getAnswer() == 'ADL.Organiseren.Hulp') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$0243e22306c849b5bb8df2097c783abf.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Organiseren, qScore, 2.0)");

end
rule "BaseTable_row_150"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$0243e22306c849b5bb8df2097c783abf : Question( getAnswer() == 'ADL.Organiseren.Hulpeloos') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$0243e22306c849b5bb8df2097c783abf.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Organiseren, qScore, 1.0)");

end
rule "BaseTable_row_151"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1e87d3dbc411478090316cca448f22b0 : Question( getAnswer() == 'ADL.Persoonlijk.Zelf') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1e87d3dbc411478090316cca448f22b0.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Persoonlijk, qScore, 5.0)");

end
rule "BaseTable_row_152"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1e87d3dbc411478090316cca448f22b0 : Question( getAnswer() == 'ADL.Persoonlijk.Zelf-') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1e87d3dbc411478090316cca448f22b0.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Persoonlijk, qScore, 4.0)");

end
rule "BaseTable_row_153"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1e87d3dbc411478090316cca448f22b0 : Question( getAnswer() == 'ADL.Persoonlijk.Moeite') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1e87d3dbc411478090316cca448f22b0.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Persoonlijk, qScore, 3.0)");

end
rule "BaseTable_row_154"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1e87d3dbc411478090316cca448f22b0 : Question( getAnswer() == 'ADL.Persoonlijk.Niet+') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1e87d3dbc411478090316cca448f22b0.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Persoonlijk, qScore, 2.0)");

end
rule "BaseTable_row_155"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$ac5eca8af8c248378b0531782105f4ca : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Activiteiten dagelijks leven') and
	$1e87d3dbc411478090316cca448f22b0 : Question( getAnswer() == 'ADL.Persoonlijk.Niet-') from $ac5eca8af8c248378b0531782105f4ca.getQuestions()
)
then
	$1e87d3dbc411478090316cca448f22b0.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (ADL.Persoonlijk, qScore, 1.0)");

end
rule "BaseTable_row_156"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$8a5a5ff13f1449f0b0a1b8dc2e10c786 : Question( getAnswer() == 'Sociaal.Familie.GoedSteun+') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$8a5a5ff13f1449f0b0a1b8dc2e10c786.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Familie, qScore, 5.0)");

end
rule "BaseTable_row_157"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$8a5a5ff13f1449f0b0a1b8dc2e10c786 : Question( getAnswer() == 'Sociaal.Familie.GoedSteun-') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$8a5a5ff13f1449f0b0a1b8dc2e10c786.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Familie, qScore, 1.0)");

end
rule "BaseTable_row_158"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$8a5a5ff13f1449f0b0a1b8dc2e10c786 : Question( getAnswer() == 'Sociaal.Familie.Regelmatig') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$8a5a5ff13f1449f0b0a1b8dc2e10c786.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Familie, qScore, 4.0)");

end
rule "BaseTable_row_159"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$8a5a5ff13f1449f0b0a1b8dc2e10c786 : Question( getAnswer() == 'Sociaal.Familie.Weinig') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$8a5a5ff13f1449f0b0a1b8dc2e10c786.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Familie, qScore, 3.0)");

end
rule "BaseTable_row_160"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$8a5a5ff13f1449f0b0a1b8dc2e10c786 : Question( getAnswer() == 'Sociaal.Familie.Nooit') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$8a5a5ff13f1449f0b0a1b8dc2e10c786.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Familie, qScore, 2.0)");

end
rule "BaseTable_row_161"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$8a5a5ff13f1449f0b0a1b8dc2e10c786 : Question( getAnswer() == 'Sociaal.Familie.Geen') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$8a5a5ff13f1449f0b0a1b8dc2e10c786.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Familie, qScore, 1.0)");

end
rule "BaseTable_row_162"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$36bed147eef44ee0b3c0ac6eca66e4ff : Question( getAnswer() == 'Sociaal.VriendenS.RegelmatigSteun+') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$36bed147eef44ee0b3c0ac6eca66e4ff.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenS, qScore, 5.0)");

end
rule "BaseTable_row_163"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$36bed147eef44ee0b3c0ac6eca66e4ff : Question( getAnswer() == 'Sociaal.VriendenS.RegelmatigSteun-') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$36bed147eef44ee0b3c0ac6eca66e4ff.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenS, qScore, 1.0)");

end
rule "BaseTable_row_164"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$36bed147eef44ee0b3c0ac6eca66e4ff : Question( getAnswer() == 'Sociaal.VriendenS.Weinig') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$36bed147eef44ee0b3c0ac6eca66e4ff.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenS, qScore, 3.0)");

end
rule "BaseTable_row_165"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$36bed147eef44ee0b3c0ac6eca66e4ff : Question( getAnswer() == 'Sociaal.VriendenS.Nooit') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$36bed147eef44ee0b3c0ac6eca66e4ff.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenS, qScore, 2.0)");

end
rule "BaseTable_row_166"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$36bed147eef44ee0b3c0ac6eca66e4ff : Question( getAnswer() == 'Sociaal.VriendenS.Geen') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$36bed147eef44ee0b3c0ac6eca66e4ff.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenS, qScore, 1.0)");

end
rule "BaseTable_row_167"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$97f103678b3c4e4986b752eccd549220 : Question( getAnswer() == 'Sociaal.VriendenR.Geen') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$97f103678b3c4e4986b752eccd549220.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenR, qScore, 5.0)");

end
rule "BaseTable_row_168"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$97f103678b3c4e4986b752eccd549220 : Question( getAnswer() == 'Sociaal.VriendenR.Een') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$97f103678b3c4e4986b752eccd549220.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenR, qScore, 4.0)");

end
rule "BaseTable_row_169"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$97f103678b3c4e4986b752eccd549220 : Question( getAnswer() == 'Sociaal.VriendenR.Hoofdzakelijk') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$97f103678b3c4e4986b752eccd549220.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.VriendenR, qScore, 2.0)");

end
rule "BaseTable_row_170"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$15835b281b8d4c39aa49a5ff0bb6251e : Question( getAnswer() == 'Sociaal.Beleving.Tevreden') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$15835b281b8d4c39aa49a5ff0bb6251e.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Beleving, qScore, 5.0)");

end
rule "BaseTable_row_171"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$15835b281b8d4c39aa49a5ff0bb6251e : Question( getAnswer() == 'Sociaal.Beleving.Minder') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$15835b281b8d4c39aa49a5ff0bb6251e.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Beleving, qScore, 3.0)");

end
rule "BaseTable_row_172"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$15835b281b8d4c39aa49a5ff0bb6251e : Question( getAnswer() == 'Sociaal.Beleving.Ontevreden') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$15835b281b8d4c39aa49a5ff0bb6251e.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Beleving, qScore, 3.0)");

end
rule "BaseTable_row_173"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$15835b281b8d4c39aa49a5ff0bb6251e : Question( getAnswer() == 'Sociaal.Beleving.Moeizaam') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$15835b281b8d4c39aa49a5ff0bb6251e.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Beleving, qScore, 2.0)");

end
rule "BaseTable_row_174"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$15835b281b8d4c39aa49a5ff0bb6251e : Question( getAnswer() == 'Sociaal.Beleving.TrekTerug') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$15835b281b8d4c39aa49a5ff0bb6251e.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Beleving, qScore, 2.0)");

end
rule "BaseTable_row_175"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f0a372fc59ca4d83a5bdd31443e7c036 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Sociaal netwerk') and
	$15835b281b8d4c39aa49a5ff0bb6251e : Question( getAnswer() == 'Sociaal.Beleving.Eenzaam') from $f0a372fc59ca4d83a5bdd31443e7c036.getQuestions()
)
then
	$15835b281b8d4c39aa49a5ff0bb6251e.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Sociaal.Beleving, qScore, 2.0)");

end
rule "BaseTable_row_176"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$88b11697111146f8925a4aaffcb44a86 : Question( getAnswer() == 'Participatie.Participatie.3+') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$88b11697111146f8925a4aaffcb44a86.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Participatie, qScore, 5.0)");

end
rule "BaseTable_row_177"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$88b11697111146f8925a4aaffcb44a86 : Question( getAnswer() == 'Participatie.Participatie.2') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$88b11697111146f8925a4aaffcb44a86.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Participatie, qScore, 4.0)");

end
rule "BaseTable_row_178"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$88b11697111146f8925a4aaffcb44a86 : Question( getAnswer() == 'Participatie.Participatie.1') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$88b11697111146f8925a4aaffcb44a86.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Participatie, qScore, 4.0)");

end
rule "BaseTable_row_179"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$88b11697111146f8925a4aaffcb44a86 : Question( getAnswer() == 'Participatie.Participatie.0') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$88b11697111146f8925a4aaffcb44a86.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Participatie, qScore, 4.0)");

end
rule "BaseTable_row_180"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.Geen') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 5.0)");

end
rule "BaseTable_row_181"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.Vervoer') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 4.0)");

end
rule "BaseTable_row_182"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.Kinderen') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 4.0)");

end
rule "BaseTable_row_183"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.BeperktZin') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 4.0)");

end
rule "BaseTable_row_184"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.Vaardigheden') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 3.0)");

end
rule "BaseTable_row_185"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.GeenZin') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 2.0)");

end
rule "BaseTable_row_186"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$c53d686ca64c4c56be494687aeacffb5 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Maatschappelijke participatie') and
	$0abf62922c5a4a929edb63b2418e3828 : Question( getAnswer() == 'Participatie.Beperkingen.LooptOver') from $c53d686ca64c4c56be494687aeacffb5.getQuestions()
)
then
	$0abf62922c5a4a929edb63b2418e3828.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Participatie.Beperkingen, qScore, 1.0)");

end
rule "BaseTable_row_187"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$8c44061df156462c8a4cd2219a675123 : Question( getAnswer() == 'Justitie.Strafblad.Geen') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$8c44061df156462c8a4cd2219a675123.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Strafblad, qScore, 5.0)");

end
rule "BaseTable_row_188"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$8c44061df156462c8a4cd2219a675123 : Question( getAnswer() == 'Justitie.Strafblad.Vergrijpen') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$8c44061df156462c8a4cd2219a675123.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Strafblad, qScore, 4.0)");

end
rule "BaseTable_row_189"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$8c44061df156462c8a4cd2219a675123 : Question( getAnswer() == 'Justitie.Strafblad.Vrijheidsstraf') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$8c44061df156462c8a4cd2219a675123.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Strafblad, qScore, 3.0)");

end
rule "BaseTable_row_190"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$8c44061df156462c8a4cd2219a675123 : Question( getAnswer() == 'Justitie.Strafblad.Actueel') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$8c44061df156462c8a4cd2219a675123.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Strafblad, qScore, 1.0)");

end
rule "BaseTable_row_191"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$4de766388c0e4a748999d190f6428174 : Question( getAnswer() == 'Jusitie.Politie.Nooit') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$4de766388c0e4a748999d190f6428174.setVariableValue('qScore', 5.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Politie, qScore, 5.0)");

end
rule "BaseTable_row_192"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$4de766388c0e4a748999d190f6428174 : Question( getAnswer() == 'Justitie.Politie.Zelden') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$4de766388c0e4a748999d190f6428174.setVariableValue('qScore', 4.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Politie, qScore, 4.0)");

end
rule "BaseTable_row_193"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$4de766388c0e4a748999d190f6428174 : Question( getAnswer() == 'Justitie.Politie.Incidenteel') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$4de766388c0e4a748999d190f6428174.setVariableValue('qScore', 3.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Politie, qScore, 3.0)");

end
rule "BaseTable_row_194"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$4de766388c0e4a748999d190f6428174 : Question( getAnswer() == 'Justitie.Politie.Regelmatig') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$4de766388c0e4a748999d190f6428174.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Politie, qScore, 2.0)");

end
rule "BaseTable_row_195"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$4de766388c0e4a748999d190f6428174 : Question( getAnswer() == 'Justitie.Politie.Overlast') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$4de766388c0e4a748999d190f6428174.setVariableValue('qScore', 2.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Politie, qScore, 2.0)");

end
rule "BaseTable_row_196"
when
(
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') and
	$4de766388c0e4a748999d190f6428174 : Question( getAnswer() == 'Justitie.Politie.Vaak') from $e856593139de4ce193b93a2b8ecef960.getQuestions()
)
then
	$4de766388c0e4a748999d190f6428174.setVariableValue('qScore', 1.0);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie.Politie, qScore, 1.0)");

end
rule "PMT_Expression"
when
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$e856593139de4ce193b93a2b8ecef960 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Justitie') 
then
	$e856593139de4ce193b93a2b8ecef960.setVariableValue('cScore', 3226.72);
	AbcdLogger.debug("DroolsRule", "Variable set (Justitie, cScore, 3226.72)");

end
rule "PMT_Rule"
when
	$2c618e2df1e04547bfca6d7ba8cb6173 : SubmittedForm() and
	$f3da6244386a4106869ef098582fee92 : Category() from $2c618e2df1e04547bfca6d7ba8cb6173.getCategory('Financiën') 
then
	$f3da6244386a4106869ef098582fee92.setVariableValue('cScore', 185.26);
	AbcdLogger.debug("DroolsRule", "Variable set (Financiën, cScore, 185.26)");

end
