package com.biit.abcd.core.drools.prattparser;

import com.biit.abcd.persistence.entity.expressions.Expression;

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
public final class ExpressionToken {

	private final ExpressionTokenType type;
	private final Expression expression;

	public ExpressionToken(ExpressionTokenType type, Expression expression) {
		this.type = type;
		this.expression = expression;
	}

	public ExpressionTokenType getType() {
		return type;
	}

	public Expression getExpression() {
		return expression;
	}

	@Override
	public String toString() {
		return expression.getRepresentation().trim();
	}

}
