package com.biit.abcd.core.drools.prattparser;

/*-
 * #%L
 * Agile Business sCenario Designer Tool (Core)
 * %%
 * Copyright (C) 2022 - 2025 BiiT Sourcing Solutions S.L.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import com.biit.abcd.persistence.entity.expressions.Expression;
import com.biit.abcd.persistence.entity.expressions.ExpressionPluginMethod;

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
public final class ExpressionToken {

	private final ExpressionTokenType type;
	private final Expression expression;
	// Identifier used to recognize the external plugin calls
	private final static String PLUGIN_INTERFACE_IDENTIFIER = "IPLUGIN";

	public ExpressionToken(ExpressionTokenType type, Expression expression) {
		this.type = type;
		this.expression = expression;
	}

	public ExpressionTokenType getType() {
		return type;
	}

	public Expression getExpression() {
		return expression;
	}

	@Override
	public String toString() {
		if (expression instanceof ExpressionPluginMethod) {
			return PLUGIN_INTERFACE_IDENTIFIER;
		} else {
			return expression.getRepresentation(true).trim();
		}
	}

}
