package com.biit.abcd.core.drools.prattparser;

import com.biit.abcd.persistence.entity.expressions.Expression;
import com.biit.abcd.persistence.entity.expressions.ExpressionPluginMethod;

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
public final class ExpressionToken {

	private final ExpressionTokenType type;
	private final Expression expression;
	// Identifier used to recognize the external plugin calls
	private final static String PLUGIN_INTERFACE_IDENTIFIER = "IPLUGIN";

	public ExpressionToken(ExpressionTokenType type, Expression expression) {
		this.type = type;
		this.expression = expression;
	}

	public ExpressionTokenType getType() {
		return type;
	}

	public Expression getExpression() {
		return expression;
	}

	@Override
	public String toString() {
		if (expression instanceof ExpressionPluginMethod) {
			return PLUGIN_INTERFACE_IDENTIFIER;
		} else {
			return expression.getRepresentation(true).trim();
		}
	}

}
