package com.biit.abcd.core.drools.prattparser.visitor;

import java.util.List;

import com.biit.abcd.core.drools.prattparser.ExpressionTokenType;
import com.biit.abcd.core.drools.prattparser.expressions.AssignExpression;
import com.biit.abcd.core.drools.prattparser.expressions.CallExpression;
import com.biit.abcd.core.drools.prattparser.expressions.ConditionalExpression;
import com.biit.abcd.core.drools.prattparser.expressions.GroupExpression;
import com.biit.abcd.core.drools.prattparser.expressions.NameExpression;
import com.biit.abcd.core.drools.prattparser.expressions.OperatorExpression;
import com.biit.abcd.core.drools.prattparser.expressions.PostfixExpression;
import com.biit.abcd.core.drools.prattparser.expressions.PrefixExpression;
import com.biit.abcd.core.drools.prattparser.visitor.exceptions.NotCompatibleTypeException;
import com.biit.abcd.core.drools.rules.validators.ExpressionValidator;
import com.biit.abcd.core.drools.rules.validators.ValueType;
import com.biit.abcd.persistence.entity.expressions.ExpressionChain;

/**
 * Visitor used to validate the expression generated by the Pratt parser
 */
public class TreeElementExpressionValidatorVisitor implements ITreeElementVisitor {

	@Override
	public void visit(AssignExpression assign) throws NotCompatibleTypeException {
		assign.getRightElement().accept(this);

		ValueType leftType = ExpressionValidator.getValueInsideExpressionChain((ExpressionChain) assign
				.getLeftExpressionChain());
		ValueType rightType = ExpressionValidator.getFirstValueInsideExpressionChain(assign.getRightElement()
				.getExpressionChain());
		if (leftType != rightType) {
			throw new NotCompatibleTypeException("Assignation types not compatible", null);
		}
	}

	@Override
	public void visit(CallExpression call) throws NotCompatibleTypeException {
		call.getLeftElement().accept(this);
		for (int i = 0; i < call.getArgs().size(); i++) {
			call.getArgs().get(i).accept(this);
		}

		// Special condition for the between
		if ((call.getFunction().getType().equals(ExpressionTokenType.BETWEEN) && (call.getArgs().size() != 2))) {
			throw new NotCompatibleTypeException("Invalid number of arguments in the between function", null);
		}
		// Rest of calls
		else if (!(call.getFunction().toString().equals("IPLUGIN"))) {
			if ((call.getArgs().size() < 1)) {
				throw new NotCompatibleTypeException("Invalid number of arguments in the call function", null);
			}
		}

		// Check the types of the arguments
		if (call.getLeftElement() instanceof NameExpression) {
			ValueType leftType = ExpressionValidator.getValueInsideExpressionChain(((NameExpression) call
					.getLeftElement()).getExpressionChain());
			checkCallArgumentsTypes(leftType, call.getArgs());
		}
	}

	private void checkCallArgumentsTypes(ValueType leftType, List<ITreeElement> args) throws NotCompatibleTypeException {
		for (ITreeElement arg : args) {
			if (arg instanceof NameExpression) {
				ValueType argumentType = ExpressionValidator.getValueInsideExpressionChain(((NameExpression) arg)
						.getExpressionChain());
				if (leftType != argumentType) {
					throw new NotCompatibleTypeException("Argument types of the call not compatible", null);
				}
			}
		}
	}

	@Override
	public void visit(ConditionalExpression condition) throws NotCompatibleTypeException {
		condition.getCondition().accept(this);
		condition.getThenArm().accept(this);
		condition.getElseArm().accept(this);
	}

	@Override
	public void visit(NameExpression name) throws NotCompatibleTypeException {
	}

	@Override
	public void visit(OperatorExpression operator) throws NotCompatibleTypeException {
		operator.getLeftElement().accept(this);
		operator.getRightElement().accept(this);
		if (!operator.getOperator().equals(ExpressionTokenType.OR)
				&& !operator.getOperator().equals(ExpressionTokenType.AND)) {
			if ((operator.getLeftElement() instanceof NameExpression)
					&& (operator.getRightElement() instanceof NameExpression)) {
				ValueType leftType = ExpressionValidator.getValueInsideExpressionChain(((NameExpression) operator
						.getLeftElement()).getExpressionChain());
				ValueType rightType = ExpressionValidator.getValueInsideExpressionChain(((NameExpression) operator
						.getRightElement()).getExpressionChain());
				if (leftType == rightType) {
					if (operator.getOperator().equals(ExpressionTokenType.PLUS)
							|| operator.getOperator().equals(ExpressionTokenType.MINUS)
							|| operator.getOperator().equals(ExpressionTokenType.MULTIPLICATION)
							|| operator.getOperator().equals(ExpressionTokenType.DIVISION)) {
						// Cannot apply the operators '+', '-', '*','/' to
						// anything but numbers
						if (!leftType.equals(ValueType.NUMBER)) {
							throw new NotCompatibleTypeException("Operator types not compatible", null);
						}
					}
				} else {
					throw new NotCompatibleTypeException("Operator types not compatible", null);
				}
			}
		} else {
			if ((operator.getLeftElement().getExpressionChain().getExpressions().size() <= 1)
					|| (operator.getRightElement().getExpressionChain().getExpressions().size() <= 1)) {
				throw new NotCompatibleTypeException("Invalid number of elements", null);
			}
		}
	}

	@Override
	public void visit(PostfixExpression postfix) throws NotCompatibleTypeException {
		postfix.getLeftElement().accept(this);
	}

	@Override
	public void visit(PrefixExpression prefix) throws NotCompatibleTypeException {
		prefix.getRightElement().accept(this);
	}

	@Override
	public void visit(GroupExpression groupExpression) throws NotCompatibleTypeException {
		groupExpression.getElement().accept(this);
	}

}
